import { createContext, useCallback, useContext, useState, type ReactNode } from "react";

// i18n — translation table copied VERBATIM from the live meet.subunit.ai (en/es/fr/it/pt).
// German is the source language: t(de) returns `de` as-is when lang==='de', else the
// mapped string (or `de` as fallback). Keys are the German source strings, 1:1 with the
// vanilla `I18N` object.
type Dict = Record<string, string>;
export const I18N: Record<string, Dict> = {
  en: {
    "Meeting aufnehmen": "Record a meeting",
    "Starte ein Meeting oder tritt einem bei. Jedes Gerät nimmt seinen eigenen Ton auf — für saubere Sprecher-Trennung.": "Start a meeting or join one. Each device records its own audio — for clean speaker separation.",
    "Meeting starten": "Start meeting",
    "Einem Meeting beitreten": "Join a meeting", "Meeting beitreten": "Join meeting", "Aufnehmen & automatisch protokollieren lassen": "Record & auto-generate minutes", "Mit Code oder Link dabei sein": "Join with code or link",
    "Meeting einrichten": "Set up meeting",
    "Angemeldet über deinen subunit.ai-Account. Konfiguriere dein Meeting und starte — Teilnehmer brauchen keinen Login.": "Signed in with your subunit.ai account. Configure your meeting and start — participants need no login.", "Angemeldet über deinen subunit.ai-Account": "Signed in with your subunit.ai account",
    "Meeting-Name": "Meeting name", "(optional)": "(optional)", "· optional": "· optional",
    "Transkription": "Transcription", "DSGVO": "GDPR", "DE-Server": "DE server", "DE-Server · sicher": "DE server · secure", "Superfast": "Superfast", "schnellste": "fastest",
    "Erfassung": "Capture", "Mehrere Geräte": "Multiple devices", "jeder sein Handy": "everyone their phone", "Ein Gerät": "One device", "ein Mik für alle": "one mic for all", "Pod-Mikro": "Pod mic", "zentral + QR": "central + QR", "Pod-Modus: Gäste scannen den QR nur zum Einchecken (Name) — nur das gewählte Mikro nimmt auf. Sprecher werden danach automatisch getrennt.": "Pod mode: guests scan the QR only to check in (name) — only the selected mic records. Speakers are separated automatically afterwards.", "Eingecheckt ✓": "Checked in ✓", "Pod nimmt auf": "Pod is recording", "Eingecheckt — warte auf Host": "Checked in — waiting for host", "Das zentrale Mikrofon nimmt das Meeting auf — du musst nichts tun. Dein Handy nimmt nichts auf. Lass diese Seite offen.": "The central microphone records the meeting — nothing for you to do. Your phone records nothing. Keep this page open.",
    "Sprache": "Language", "Wie viele sprechen?": "How many speakers?", "Namen": "Names", "(optional — später im Transkript zuordenbar)": "(optional — assignable in the transcript later)",
    "Zurück": "Back", "Abbrechen": "Cancel", "Kopieren": "Copy", "Senden": "Send", "Download": "Download", "Transkript": "Transcript", "PDF": "PDF", "An Teilnehmer": "To participants", "Gedächtnis": "Memory", "Notion": "Notion", "Zusammenfassung": "Summary",
    "Dein Meeting": "Your meeting", "Bereit — Aufnahme noch nicht gestartet": "Ready — recording not started yet", "Mikro an": "Mic on", "Mikro aus": "Mic off",
    "📵 Gerät NICHT sperren & in dieser App bleiben — sonst pausiert die Aufnahme.": "📵 Do NOT lock the device & stay in this app — otherwise recording pauses.",
    "Beitritts-Code": "Join code", "Oder Link teilen": "Or share link", "Teilnehmer": "Participants", "Noch niemand beigetreten…": "Nobody has joined yet…",
    "Ein-Geräte-Meeting": "Single-device meeting", "Alle sprechen über dieses Mikro. Starte die Aufnahme, wenn ihr bereit seid.": "Everyone speaks through this mic. Start recording when you're ready.",
    "Gib den 6-stelligen Code ein, den der Host teilt.": "Enter the 6-digit code the host shares.", "Meeting-Code": "Meeting code", "Dein Name": "Your name", "E-Mail": "Email", "name@firma.de — optional": "name@company.com — optional", "Beitreten": "Join",
    "Im Warteraum": "In the waiting room", "Der Host muss dich noch freigeben…": "The host still needs to admit you…", "Sobald der Host dich freigibt, startet deine Aufnahme automatisch.": "Once the host admits you, your recording starts automatically.", "Sobald der Host dich freigibt, bist du dabei.": "Once the host admits you, you're in.",
    "🔴 Aufnahme manuell starten": "🔴 Start recording manually", "Meeting verlassen": "Leave meeting", "Du bist dabei": "You're in", "Warte auf Host…": "Waiting for host…", "Sobald der Host startet, nimmt dein Gerät automatisch auf. Leg das Handy hin.": "Once the host starts, your device records automatically. Put the phone down.",
    "Meeting beendet": "Meeting ended", "Dein Deep-Dive wird erstellt — Transkript, Themen, Entscheidungen.": "Your deep-dive is being created — transcript, topics, decisions.",
    "Protokoll senden an…": "Send minutes to…", "Wähle die Empfänger. Fehlt eine E-Mail, kannst du sie hier eintragen.": "Choose the recipients. If an email is missing, you can add it here.", "Freigeben": "Admit", "Zur Startseite": "To home",
    "Protokoll-Sprache": "Minutes language", "Original-Sprache": "Original language", "Deutsch": "German", "Englisch": "English", "Spanisch": "Spanish", "Französisch": "French", "Italienisch": "Italian", "🌐 Automatisch erkennen": "🌐 Auto-detect", "🇩🇪 Deutsch": "🇩🇪 German", "🇬🇧 Englisch": "🇬🇧 English", "🇪🇸 Spanisch": "🇪🇸 Spanish", "🇫🇷 Französisch": "🇫🇷 French", "🇮🇹 Italienisch": "🇮🇹 Italian",
    "Meeting wird erstellt…": "Creating meeting…", "Trete bei…": "Joining…", "Sende…": "Sending…", "Verbindungsfehler.": "Connection error.", "Verbindungsfehler beim Erstellen.": "Connection error while creating.", "Host-Beitritt fehlgeschlagen.": "Host join failed.", "6-stelliger Code nötig.": "6-digit code required.", "Bitte Namen eingeben.": "Please enter a name.", "E-Mail sieht ungültig aus — korrigieren oder leer lassen.": "Email looks invalid — fix it or leave it empty.", "Beitritt fehlgeschlagen (Code korrekt? Meeting noch offen?).": "Join failed (is the code correct? is the meeting still open?).", "Meeting konnte nicht erstellt werden (Account-Zugang?).": "Could not create the meeting (account access?).", "Netzwerkfehler.": "Network error.", "Aufnahme war unterbrochen — hier fortsetzen": "Recording was interrupted — resume here", "Kopiert ✓": "Copied ✓", "Geladen ✓": "Downloaded ✓", "Transkript ✓": "Transcript ✓", "Mikrofon": "Microphone", "Standard-Mikrofon": "Default microphone", "Für ein zentrales Mikro (z. B. Jabra) hier das Gerät wählen — dann nimmt nur dieses auf.": "For a central mic (e.g. Jabra), pick the device here — then only this one records.", "Stimm-Check-In": "Voice check-in", "Jeder liest seine Zahl vor — der Pod erkennt die Stimme und ordnet den Namen automatisch zu.": "Everyone reads their number aloud — the pod recognises the voice and assigns the name automatically.", "Stimm-Check-In starten": "Start voice check-in", "Starte…": "Starting…", "Du bist dran": "Your turn", "Lies deine Zahl laut vor:": "Read your number aloud:", "Sprich deutlich Richtung Pod-Mikro.": "Speak clearly toward the pod mic.", "Der Pod hört zu…": "The pod is listening…", "Geschafft": "Done", "Eingecheckt!": "Checked in!", "Alle dabei — es kann losgehen.": "Everyone's in — let's go.", "Stimme erkannt. Du kannst das Handy weglegen.": "Voice recognised. You can put your phone away.", "liest gerade vor…": "is reading now…", "Gleich geht's los…": "Starting in a moment…", "Gleich bist du dran — halt dich bereit.": "You're up next — get ready.", "eingecheckt": "checked in", "✓ erkannt": "✓ recognised", "Test-Trigger (bis das echte Jabra die Zahl hört)": "Test trigger (until the real Jabra hears the number)", "Überspringen": "Skip", "übersprungen": "skipped", "wartet": "waiting", "Alle eingecheckt ✓ — Aufnahme starten": "All checked in ✓ — start recording",
  },
  es: {
    "Meeting aufnehmen": "Grabar una reunión",
    "Starte ein Meeting oder tritt einem bei. Jedes Gerät nimmt seinen eigenen Ton auf — für saubere Sprecher-Trennung.": "Inicia una reunión o únete a una. Cada dispositivo graba su propio audio — para una separación limpia de los hablantes.",
    "Meeting starten": "Iniciar reunión",
    "Einem Meeting beitreten": "Unirse a una reunión", "Meeting beitreten": "Unirse a la reunión", "Aufnehmen & automatisch protokollieren lassen": "Grabar y generar el acta automáticamente", "Mit Code oder Link dabei sein": "Únete con código o enlace",
    "Meeting einrichten": "Configurar reunión",
    "Angemeldet über deinen subunit.ai-Account. Konfiguriere dein Meeting und starte — Teilnehmer brauchen keinen Login.": "Conectado con tu cuenta de subunit.ai. Configura tu reunión e inicia — los participantes no necesitan iniciar sesión.", "Angemeldet über deinen subunit.ai-Account": "Conectado con tu cuenta de subunit.ai",
    "Meeting-Name": "Nombre de la reunión", "(optional)": "(opcional)", "· optional": "· opcional",
    "Transkription": "Transcripción", "DSGVO": "RGPD", "DE-Server": "Servidor DE", "DE-Server · sicher": "Servidor DE · seguro", "Superfast": "Superrápido", "schnellste": "el más rápido",
    "Erfassung": "Captura", "Mehrere Geräte": "Varios dispositivos", "jeder sein Handy": "cada uno su móvil", "Ein Gerät": "Un dispositivo", "ein Mik für alle": "un micro para todos", "Pod-Mikro": "Micro pod", "zentral + QR": "central + QR", "Pod-Modus: Gäste scannen den QR nur zum Einchecken (Name) — nur das gewählte Mikro nimmt auf. Sprecher werden danach automatisch getrennt.": "Modo pod: los invitados escanean el QR solo para registrarse (nombre) — solo graba el micro seleccionado. Los hablantes se separan automáticamente después.", "Eingecheckt ✓": "Registrado ✓", "Pod nimmt auf": "El pod está grabando", "Eingecheckt — warte auf Host": "Registrado — esperando al anfitrión", "Das zentrale Mikrofon nimmt das Meeting auf — du musst nichts tun. Dein Handy nimmt nichts auf. Lass diese Seite offen.": "El micrófono central graba la reunión — no tienes que hacer nada. Tu móvil no graba nada. Deja esta página abierta.",
    "Sprache": "Idioma", "Wie viele sprechen?": "¿Cuántos hablan?", "Namen": "Nombres", "(optional — später im Transkript zuordenbar)": "(opcional — asignable en la transcripción después)",
    "Zurück": "Atrás", "Abbrechen": "Cancelar", "Kopieren": "Copiar", "Senden": "Enviar", "Download": "Descargar", "Transkript": "Transcripción", "PDF": "PDF", "An Teilnehmer": "A los participantes", "Gedächtnis": "Memoria", "Notion": "Notion", "Zusammenfassung": "Resumen",
    "Dein Meeting": "Tu reunión", "Bereit — Aufnahme noch nicht gestartet": "Listo — grabación aún no iniciada", "Mikro an": "Micro activado", "Mikro aus": "Micro silenciado",
    "📵 Gerät NICHT sperren & in dieser App bleiben — sonst pausiert die Aufnahme.": "📵 NO bloquees el dispositivo y permanece en esta app — si no, la grabación se pausa.",
    "Beitritts-Code": "Código de acceso", "Oder Link teilen": "O comparte el enlace", "Teilnehmer": "Participantes", "Noch niemand beigetreten…": "Nadie se ha unido todavía…",
    "Ein-Geräte-Meeting": "Reunión de un dispositivo", "Alle sprechen über dieses Mikro. Starte die Aufnahme, wenn ihr bereit seid.": "Todos hablan por este micro. Inicia la grabación cuando estéis listos.",
    "Gib den 6-stelligen Code ein, den der Host teilt.": "Introduce el código de 6 dígitos que comparte el anfitrión.", "Meeting-Code": "Código de reunión", "Dein Name": "Tu nombre", "E-Mail": "Correo", "name@firma.de — optional": "nombre@empresa.com — opcional", "Beitreten": "Unirse",
    "Im Warteraum": "En la sala de espera", "Der Host muss dich noch freigeben…": "El anfitrión aún debe admitirte…", "Sobald der Host dich freigibt, startet deine Aufnahme automatisch.": "En cuanto el anfitrión te admita, tu grabación comienza automáticamente.", "Sobald der Host dich freigibt, bist du dabei.": "En cuanto el anfitrión te admita, estás dentro.",
    "🔴 Aufnahme manuell starten": "🔴 Iniciar grabación manualmente", "Meeting verlassen": "Salir de la reunión", "Du bist dabei": "Estás dentro", "Warte auf Host…": "Esperando al anfitrión…", "Sobald der Host startet, nimmt dein Gerät automatisch auf. Leg das Handy hin.": "En cuanto el anfitrión empiece, tu dispositivo graba automáticamente. Deja el móvil.",
    "Meeting beendet": "Reunión finalizada", "Dein Deep-Dive wird erstellt — Transkript, Themen, Entscheidungen.": "Se está creando tu análisis — transcripción, temas, decisiones.",
    "Protokoll senden an…": "Enviar acta a…", "Wähle die Empfänger. Fehlt eine E-Mail, kannst du sie hier eintragen.": "Elige los destinatarios. Si falta un correo, puedes añadirlo aquí.", "Freigeben": "Admitir", "Zur Startseite": "A inicio",
    "Protokoll-Sprache": "Idioma del acta", "Original-Sprache": "Idioma original", "Deutsch": "Alemán", "Englisch": "Inglés", "Spanisch": "Español", "Französisch": "Francés", "Italienisch": "Italiano", "🌐 Automatisch erkennen": "🌐 Detección automática", "🇩🇪 Deutsch": "🇩🇪 Alemán", "🇬🇧 Englisch": "🇬🇧 Inglés", "🇪🇸 Spanisch": "🇪🇸 Español", "🇫🇷 Französisch": "🇫🇷 Francés", "🇮🇹 Italienisch": "🇮🇹 Italiano",
    "Meeting wird erstellt…": "Creando reunión…", "Trete bei…": "Uniéndose…", "Sende…": "Enviando…", "Verbindungsfehler.": "Error de conexión.", "Verbindungsfehler beim Erstellen.": "Error de conexión al crear.", "Host-Beitritt fehlgeschlagen.": "Fallo al unirse como anfitrión.", "6-stelliger Code nötig.": "Se requiere un código de 6 dígitos.", "Bitte Namen eingeben.": "Introduce un nombre.", "E-Mail sieht ungültig aus — korrigieren oder leer lassen.": "El correo parece inválido — corrígelo o déjalo vacío.", "Beitritt fehlgeschlagen (Code korrekt? Meeting noch offen?).": "Fallo al unirse (¿código correcto? ¿reunión abierta?).", "Meeting konnte nicht erstellt werden (Account-Zugang?).": "No se pudo crear la reunión (¿acceso a la cuenta?).", "Netzwerkfehler.": "Error de red.", "Aufnahme war unterbrochen — hier fortsetzen": "La grabación se interrumpió — reanudar aquí", "Kopiert ✓": "Copiado ✓", "Geladen ✓": "Descargado ✓", "Transkript ✓": "Transcripción ✓", "Mikrofon": "Micrófono", "Standard-Mikrofon": "Micrófono predeterminado", "Für ein zentrales Mikro (z. B. Jabra) hier das Gerät wählen — dann nimmt nur dieses auf.": "Para un micro central (p. ej. Jabra), elige aquí el dispositivo — así solo este graba.", "Stimm-Check-In": "Registro por voz", "Jeder liest seine Zahl vor — der Pod erkennt die Stimme und ordnet den Namen automatisch zu.": "Cada uno lee su número en voz alta — el pod reconoce la voz y asigna el nombre automáticamente.", "Stimm-Check-In starten": "Iniciar registro por voz", "Starte…": "Iniciando…", "Du bist dran": "Es tu turno", "Lies deine Zahl laut vor:": "Lee tu número en voz alta:", "Sprich deutlich Richtung Pod-Mikro.": "Habla claro hacia el micro del pod.", "Der Pod hört zu…": "El pod está escuchando…", "Geschafft": "Listo", "Eingecheckt!": "¡Registrado!", "Alle dabei — es kann losgehen.": "Todos dentro — ¡a empezar!", "Stimme erkannt. Du kannst das Handy weglegen.": "Voz reconocida. Puedes dejar el móvil.", "liest gerade vor…": "está leyendo ahora…", "Gleich geht's los…": "Empezamos enseguida…", "Gleich bist du dran — halt dich bereit.": "Eres el siguiente — prepárate.", "eingecheckt": "registrados", "✓ erkannt": "✓ reconocido", "Test-Trigger (bis das echte Jabra die Zahl hört)": "Disparador de prueba (hasta que el Jabra real oiga el número)", "Überspringen": "Saltar", "übersprungen": "saltado", "wartet": "esperando", "Alle eingecheckt ✓ — Aufnahme starten": "Todos registrados ✓ — iniciar grabación",
  },
  fr: {
    "Meeting aufnehmen": "Enregistrer une réunion",
    "Starte ein Meeting oder tritt einem bei. Jedes Gerät nimmt seinen eigenen Ton auf — für saubere Sprecher-Trennung.": "Démarrez une réunion ou rejoignez-en une. Chaque appareil enregistre son propre audio — pour une séparation nette des intervenants.",
    "Meeting starten": "Démarrer la réunion", "Einem Meeting beitreten": "Rejoindre une réunion", "Meeting beitreten": "Rejoindre la réunion", "Aufnehmen & automatisch protokollieren lassen": "Enregistrer et générer le compte rendu automatiquement", "Mit Code oder Link dabei sein": "Rejoindre avec un code ou un lien", "Meeting einrichten": "Configurer la réunion",
    "Angemeldet über deinen subunit.ai-Account. Konfiguriere dein Meeting und starte — Teilnehmer brauchen keinen Login.": "Connecté avec votre compte subunit.ai. Configurez votre réunion et démarrez — les participants n'ont pas besoin de se connecter.", "Angemeldet über deinen subunit.ai-Account": "Connecté avec votre compte subunit.ai",
    "Meeting-Name": "Nom de la réunion", "(optional)": "(facultatif)", "· optional": "· facultatif", "Transkription": "Transcription", "DSGVO": "RGPD", "DE-Server": "Serveur DE", "DE-Server · sicher": "Serveur DE · sécurisé", "Superfast": "Ultra-rapide", "schnellste": "le plus rapide",
    "Erfassung": "Capture", "Mehrere Geräte": "Plusieurs appareils", "jeder sein Handy": "chacun son téléphone", "Ein Gerät": "Un appareil", "ein Mik für alle": "un micro pour tous", "Pod-Mikro": "Micro pod", "zentral + QR": "central + QR", "Pod-Modus: Gäste scannen den QR nur zum Einchecken (Name) — nur das gewählte Mikro nimmt auf. Sprecher werden danach automatisch getrennt.": "Mode pod : les invités scannent le QR seulement pour s'enregistrer (nom) — seul le micro sélectionné enregistre. Les intervenants sont séparés automatiquement ensuite.", "Eingecheckt ✓": "Enregistré ✓", "Pod nimmt auf": "Le pod enregistre", "Eingecheckt — warte auf Host": "Enregistré — en attente de l'hôte", "Das zentrale Mikrofon nimmt das Meeting auf — du musst nichts tun. Dein Handy nimmt nichts auf. Lass diese Seite offen.": "Le microphone central enregistre la réunion — rien à faire pour toi. Ton téléphone n'enregistre rien. Garde cette page ouverte.",
    "Sprache": "Langue", "Wie viele sprechen?": "Combien de personnes parlent ?", "Namen": "Noms", "(optional — später im Transkript zuordenbar)": "(facultatif — assignable dans la transcription ensuite)",
    "Zurück": "Retour", "Abbrechen": "Annuler", "Kopieren": "Copier", "Senden": "Envoyer", "Download": "Télécharger", "Transkript": "Transcription", "PDF": "PDF", "An Teilnehmer": "Aux participants", "Gedächtnis": "Mémoire", "Notion": "Notion", "Zusammenfassung": "Résumé",
    "Dein Meeting": "Votre réunion", "Bereit — Aufnahme noch nicht gestartet": "Prêt — enregistrement pas encore démarré", "Mikro an": "Micro activé", "Mikro aus": "Micro coupé",
    "📵 Gerät NICHT sperren & in dieser App bleiben — sonst pausiert die Aufnahme.": "📵 NE verrouillez PAS l'appareil et restez dans cette app — sinon l'enregistrement se met en pause.",
    "Beitritts-Code": "Code d'accès", "Oder Link teilen": "Ou partagez le lien", "Teilnehmer": "Participants", "Noch niemand beigetreten…": "Personne n'a encore rejoint…",
    "Ein-Geräte-Meeting": "Réunion mono-appareil", "Alle sprechen über dieses Mikro. Starte die Aufnahme, wenn ihr bereit seid.": "Tout le monde parle dans ce micro. Démarrez l'enregistrement quand vous êtes prêts.",
    "Gib den 6-stelligen Code ein, den der Host teilt.": "Saisissez le code à 6 chiffres partagé par l'hôte.", "Meeting-Code": "Code de réunion", "Dein Name": "Votre nom", "E-Mail": "E-mail", "name@firma.de — optional": "nom@entreprise.fr — facultatif", "Beitreten": "Rejoindre",
    "Im Warteraum": "Dans la salle d'attente", "Der Host muss dich noch freigeben…": "L'hôte doit encore vous admettre…", "Sobald der Host dich freigibt, startet deine Aufnahme automatisch.": "Dès que l'hôte vous admet, votre enregistrement démarre automatiquement.", "Sobald der Host dich freigibt, bist du dabei.": "Dès que l'hôte vous admet, vous êtes dans la réunion.",
    "🔴 Aufnahme manuell starten": "🔴 Démarrer l'enregistrement manuellement", "Meeting verlassen": "Quitter la réunion", "Du bist dabei": "Vous êtes dans la réunion", "Warte auf Host…": "En attente de l'hôte…", "Sobald der Host startet, nimmt dein Gerät automatisch auf. Leg das Handy hin.": "Dès que l'hôte démarre, ton appareil enregistre automatiquement. Pose le téléphone.",
    "Meeting beendet": "Réunion terminée", "Dein Deep-Dive wird erstellt — Transkript, Themen, Entscheidungen.": "Votre analyse est en cours — transcription, sujets, décisions.",
    "Protokoll senden an…": "Envoyer le compte rendu à…", "Wähle die Empfänger. Fehlt eine E-Mail, kannst du sie hier eintragen.": "Choisissez les destinataires. S'il manque un e-mail, ajoutez-le ici.", "Freigeben": "Admettre", "Zur Startseite": "Accueil",
    "Protokoll-Sprache": "Langue du compte rendu", "Original-Sprache": "Langue d'origine", "Deutsch": "Allemand", "Englisch": "Anglais", "Spanisch": "Espagnol", "Französisch": "Français", "Italienisch": "Italien", "🌐 Automatisch erkennen": "🌐 Détection automatique",
    "🇩🇪 Deutsch": "🇩🇪 Allemand", "🇬🇧 Englisch": "🇬🇧 Anglais", "🇪🇸 Spanisch": "🇪🇸 Espagnol", "🇫🇷 Französisch": "🇫🇷 Français", "🇮🇹 Italienisch": "🇮🇹 Italien",
    "Meeting wird erstellt…": "Création de la réunion…", "Trete bei…": "Connexion…", "Sende…": "Envoi…", "Verbindungsfehler.": "Erreur de connexion.", "Verbindungsfehler beim Erstellen.": "Erreur de connexion lors de la création.", "Host-Beitritt fehlgeschlagen.": "Échec de la connexion de l'hôte.", "6-stelliger Code nötig.": "Code à 6 chiffres requis.", "Bitte Namen eingeben.": "Veuillez saisir un nom.", "E-Mail sieht ungültig aus — korrigieren oder leer lassen.": "L'e-mail semble invalide — corrigez-le ou laissez-le vide.", "Beitritt fehlgeschlagen (Code korrekt? Meeting noch offen?).": "Échec de l'accès (code correct ? réunion encore ouverte ?).", "Meeting konnte nicht erstellt werden (Account-Zugang?).": "Impossible de créer la réunion (accès au compte ?).", "Netzwerkfehler.": "Erreur réseau.", "Aufnahme war unterbrochen — hier fortsetzen": "L'enregistrement a été interrompu — reprendre ici", "Kopiert ✓": "Copié ✓", "Geladen ✓": "Téléchargé ✓", "Transkript ✓": "Transcription ✓", "Mikrofon": "Microphone", "Standard-Mikrofon": "Microphone par défaut", "Für ein zentrales Mikro (z. B. Jabra) hier das Gerät wählen — dann nimmt nur dieses auf.": "Pour un micro central (p. ex. Jabra), choisissez l'appareil ici — ainsi seul celui-ci enregistre.", "Stimm-Check-In": "Enregistrement vocal", "Jeder liest seine Zahl vor — der Pod erkennt die Stimme und ordnet den Namen automatisch zu.": "Chacun lit son numéro à voix haute — le pod reconnaît la voix et attribue le nom automatiquement.", "Stimm-Check-In starten": "Démarrer l'enregistrement vocal", "Starte…": "Démarrage…", "Du bist dran": "À toi", "Lies deine Zahl laut vor:": "Lis ton numéro à voix haute :", "Sprich deutlich Richtung Pod-Mikro.": "Parle clairement vers le micro du pod.", "Der Pod hört zu…": "Le pod écoute…", "Geschafft": "Terminé", "Eingecheckt!": "Enregistré !", "Alle dabei — es kann losgehen.": "Tout le monde est là — c'est parti.", "Stimme erkannt. Du kannst das Handy weglegen.": "Voix reconnue. Tu peux poser ton téléphone.", "liest gerade vor…": "lit en ce moment…", "Gleich geht's los…": "On commence tout de suite…", "Gleich bist du dran — halt dich bereit.": "C'est bientôt ton tour — tiens-toi prêt.", "eingecheckt": "enregistrés", "✓ erkannt": "✓ reconnu", "Test-Trigger (bis das echte Jabra die Zahl hört)": "Déclencheur de test (jusqu'à ce que le vrai Jabra entende le numéro)", "Überspringen": "Passer", "übersprungen": "passé", "wartet": "en attente", "Alle eingecheckt ✓ — Aufnahme starten": "Tous enregistrés ✓ — démarrer l'enregistrement",
  },
  it: {
    "Meeting aufnehmen": "Registra una riunione",
    "Starte ein Meeting oder tritt einem bei. Jedes Gerät nimmt seinen eigenen Ton auf — für saubere Sprecher-Trennung.": "Avvia una riunione o uniscicene a una. Ogni dispositivo registra il proprio audio — per una netta separazione degli interlocutori.",
    "Meeting starten": "Avvia riunione", "Einem Meeting beitreten": "Partecipa a una riunione", "Meeting beitreten": "Partecipa alla riunione", "Aufnehmen & automatisch protokollieren lassen": "Registra e genera il verbale automaticamente", "Mit Code oder Link dabei sein": "Partecipa con codice o link", "Meeting einrichten": "Configura riunione",
    "Angemeldet über deinen subunit.ai-Account. Konfiguriere dein Meeting und starte — Teilnehmer brauchen keinen Login.": "Connesso con il tuo account subunit.ai. Configura la riunione e avvia — i partecipanti non devono accedere.", "Angemeldet über deinen subunit.ai-Account": "Connesso con il tuo account subunit.ai",
    "Meeting-Name": "Nome della riunione", "(optional)": "(facoltativo)", "· optional": "· facoltativo", "Transkription": "Trascrizione", "DSGVO": "GDPR", "DE-Server": "Server DE", "DE-Server · sicher": "Server DE · sicuro", "Superfast": "Velocissimo", "schnellste": "il più veloce",
    "Erfassung": "Acquisizione", "Mehrere Geräte": "Più dispositivi", "jeder sein Handy": "ognuno il suo telefono", "Ein Gerät": "Un dispositivo", "ein Mik für alle": "un microfono per tutti", "Pod-Mikro": "Micro pod", "zentral + QR": "centrale + QR", "Pod-Modus: Gäste scannen den QR nur zum Einchecken (Name) — nur das gewählte Mikro nimmt auf. Sprecher werden danach automatisch getrennt.": "Modalità pod: gli ospiti scansionano il QR solo per registrarsi (nome) — registra solo il microfono selezionato. Gli interlocutori vengono separati automaticamente dopo.", "Eingecheckt ✓": "Registrato ✓", "Pod nimmt auf": "Il pod sta registrando", "Eingecheckt — warte auf Host": "Registrato — in attesa dell'host", "Das zentrale Mikrofon nimmt das Meeting auf — du musst nichts tun. Dein Handy nimmt nichts auf. Lass diese Seite offen.": "Il microfono centrale registra la riunione — non devi fare nulla. Il tuo telefono non registra niente. Lascia questa pagina aperta.",
    "Sprache": "Lingua", "Wie viele sprechen?": "Quanti parlano?", "Namen": "Nomi", "(optional — später im Transkript zuordenbar)": "(facoltativo — assegnabile nella trascrizione dopo)",
    "Zurück": "Indietro", "Abbrechen": "Annulla", "Kopieren": "Copia", "Senden": "Invia", "Download": "Scarica", "Transkript": "Trascrizione", "PDF": "PDF", "An Teilnehmer": "Ai partecipanti", "Gedächtnis": "Memoria", "Notion": "Notion", "Zusammenfassung": "Riepilogo",
    "Dein Meeting": "La tua riunione", "Bereit — Aufnahme noch nicht gestartet": "Pronto — registrazione non ancora avviata", "Mikro an": "Microfono acceso", "Mikro aus": "Microfono spento",
    "📵 Gerät NICHT sperren & in dieser App bleiben — sonst pausiert die Aufnahme.": "📵 NON bloccare il dispositivo e resta in questa app — altrimenti la registrazione si mette in pausa.",
    "Beitritts-Code": "Codice di accesso", "Oder Link teilen": "Oppure condividi il link", "Teilnehmer": "Partecipanti", "Noch niemand beigetreten…": "Nessuno si è ancora unito…",
    "Ein-Geräte-Meeting": "Riunione a dispositivo singolo", "Alle sprechen über dieses Mikro. Starte die Aufnahme, wenn ihr bereit seid.": "Tutti parlano in questo microfono. Avvia la registrazione quando siete pronti.",
    "Gib den 6-stelligen Code ein, den der Host teilt.": "Inserisci il codice a 6 cifre condiviso dall'organizzatore.", "Meeting-Code": "Codice riunione", "Dein Name": "Il tuo nome", "E-Mail": "E-mail", "name@firma.de — optional": "nome@azienda.it — facoltativo", "Beitreten": "Partecipa",
    "Im Warteraum": "In sala d'attesa", "Der Host muss dich noch freigeben…": "L'organizzatore deve ancora ammetterti…", "Sobald der Host dich freigibt, startet deine Aufnahme automatisch.": "Appena l'organizzatore ti ammette, la tua registrazione parte automaticamente.", "Sobald der Host dich freigibt, bist du dabei.": "Appena l'organizzatore ti ammette, sei dentro.",
    "🔴 Aufnahme manuell starten": "🔴 Avvia registrazione manualmente", "Meeting verlassen": "Esci dalla riunione", "Du bist dabei": "Sei dentro", "Warte auf Host…": "In attesa dell'host…", "Sobald der Host startet, nimmt dein Gerät automatisch auf. Leg das Handy hin.": "Appena l'host avvia, il tuo dispositivo registra automaticamente. Posa il telefono.",
    "Meeting beendet": "Riunione terminata", "Dein Deep-Dive wird erstellt — Transkript, Themen, Entscheidungen.": "La tua analisi è in preparazione — trascrizione, temi, decisioni.",
    "Protokoll senden an…": "Invia il verbale a…", "Wähle die Empfänger. Fehlt eine E-Mail, kannst du sie hier eintragen.": "Scegli i destinatari. Se manca un'e-mail, puoi aggiungerla qui.", "Freigeben": "Ammetti", "Zur Startseite": "Alla home",
    "Protokoll-Sprache": "Lingua del verbale", "Original-Sprache": "Lingua originale", "Deutsch": "Tedesco", "Englisch": "Inglese", "Spanisch": "Spagnolo", "Französisch": "Francese", "Italienisch": "Italiano", "🌐 Automatisch erkennen": "🌐 Rilevamento automatico",
    "🇩🇪 Deutsch": "🇩🇪 Tedesco", "🇬🇧 Englisch": "🇬🇧 Inglese", "🇪🇸 Spanisch": "🇪🇸 Spagnolo", "🇫🇷 Französisch": "🇫🇷 Francese", "🇮🇹 Italienisch": "🇮🇹 Italiano",
    "Meeting wird erstellt…": "Creazione della riunione…", "Trete bei…": "Accesso…", "Sende…": "Invio…", "Verbindungsfehler.": "Errore di connessione.", "Verbindungsfehler beim Erstellen.": "Errore di connessione durante la creazione.", "Host-Beitritt fehlgeschlagen.": "Accesso dell'organizzatore non riuscito.", "6-stelliger Code nötig.": "Serve un codice a 6 cifre.", "Bitte Namen eingeben.": "Inserisci un nome.", "E-Mail sieht ungültig aus — korrigieren oder leer lassen.": "L'e-mail sembra non valida — correggila o lasciala vuota.", "Beitritt fehlgeschlagen (Code korrekt? Meeting noch offen?).": "Accesso non riuscito (codice corretto? riunione ancora aperta?).", "Meeting konnte nicht erstellt werden (Account-Zugang?).": "Impossibile creare la riunione (accesso all'account?).", "Netzwerkfehler.": "Errore di rete.", "Aufnahme war unterbrochen — hier fortsetzen": "La registrazione è stata interrotta — riprendi qui", "Kopiert ✓": "Copiato ✓", "Geladen ✓": "Scaricato ✓", "Transkript ✓": "Trascrizione ✓", "Mikrofon": "Microfono", "Standard-Mikrofon": "Microfono predefinito", "Für ein zentrales Mikro (z. B. Jabra) hier das Gerät wählen — dann nimmt nur dieses auf.": "Per un microfono centrale (es. Jabra), seleziona qui il dispositivo — così registra solo questo.", "Stimm-Check-In": "Check-in vocale", "Jeder liest seine Zahl vor — der Pod erkennt die Stimme und ordnet den Namen automatisch zu.": "Ognuno legge il proprio numero ad alta voce — il pod riconosce la voce e assegna il nome automaticamente.", "Stimm-Check-In starten": "Avvia il check-in vocale", "Starte…": "Avvio…", "Du bist dran": "Tocca a te", "Lies deine Zahl laut vor:": "Leggi il tuo numero ad alta voce:", "Sprich deutlich Richtung Pod-Mikro.": "Parla chiaramente verso il microfono del pod.", "Der Pod hört zu…": "Il pod sta ascoltando…", "Geschafft": "Fatto", "Eingecheckt!": "Registrato!", "Alle dabei — es kann losgehen.": "Ci sono tutti — si parte.", "Stimme erkannt. Du kannst das Handy weglegen.": "Voce riconosciuta. Puoi posare il telefono.", "liest gerade vor…": "sta leggendo ora…", "Gleich geht's los…": "Si comincia tra poco…", "Gleich bist du dran — halt dich bereit.": "Tocca a te tra poco — tieniti pronto.", "eingecheckt": "registrati", "✓ erkannt": "✓ riconosciuto", "Test-Trigger (bis das echte Jabra die Zahl hört)": "Trigger di prova (finché il vero Jabra sente il numero)", "Überspringen": "Salta", "übersprungen": "saltato", "wartet": "in attesa", "Alle eingecheckt ✓ — Aufnahme starten": "Tutti registrati ✓ — avvia la registrazione",
  },
  pt: {
    "Meeting aufnehmen": "Gravar uma reunião",
    "Starte ein Meeting oder tritt einem bei. Jedes Gerät nimmt seinen eigenen Ton auf — für saubere Sprecher-Trennung.": "Inicie uma reunião ou junte-se a uma. Cada dispositivo grava o seu próprio áudio — para uma separação limpa dos oradores.",
    "Meeting starten": "Iniciar reunião", "Einem Meeting beitreten": "Juntar-se a uma reunião", "Meeting beitreten": "Juntar-se à reunião", "Aufnehmen & automatisch protokollieren lassen": "Gravar e gerar a ata automaticamente", "Mit Code oder Link dabei sein": "Junte-se com código ou link", "Meeting einrichten": "Configurar reunião",
    "Angemeldet über deinen subunit.ai-Account. Konfiguriere dein Meeting und starte — Teilnehmer brauchen keinen Login.": "Ligado com a sua conta subunit.ai. Configure a reunião e inicie — os participantes não precisam de iniciar sessão.", "Angemeldet über deinen subunit.ai-Account": "Ligado com a sua conta subunit.ai",
    "Meeting-Name": "Nome da reunião", "(optional)": "(opcional)", "· optional": "· opcional", "Transkription": "Transcrição", "DSGVO": "RGPD", "DE-Server": "Servidor DE", "DE-Server · sicher": "Servidor DE · seguro", "Superfast": "Super-rápido", "schnellste": "o mais rápido",
    "Erfassung": "Captura", "Mehrere Geräte": "Vários dispositivos", "jeder sein Handy": "cada um o seu telemóvel", "Ein Gerät": "Um dispositivo", "ein Mik für alle": "um micro para todos", "Pod-Mikro": "Micro pod", "zentral + QR": "central + QR", "Pod-Modus: Gäste scannen den QR nur zum Einchecken (Name) — nur das gewählte Mikro nimmt auf. Sprecher werden danach automatisch getrennt.": "Modo pod: os convidados leem o QR apenas para fazer check-in (nome) — só o micro selecionado grava. Os oradores são separados automaticamente depois.", "Eingecheckt ✓": "Check-in feito ✓", "Pod nimmt auf": "O pod está a gravar", "Eingecheckt — warte auf Host": "Check-in feito — à espera do anfitrião", "Das zentrale Mikrofon nimmt das Meeting auf — du musst nichts tun. Dein Handy nimmt nichts auf. Lass diese Seite offen.": "O microfone central grava a reunião — não tens de fazer nada. O teu telemóvel não grava nada. Deixa esta página aberta.",
    "Sprache": "Idioma", "Wie viele sprechen?": "Quantos falam?", "Namen": "Nomes", "(optional — später im Transkript zuordenbar)": "(opcional — atribuível na transcrição depois)",
    "Zurück": "Voltar", "Abbrechen": "Cancelar", "Kopieren": "Copiar", "Senden": "Enviar", "Download": "Transferir", "Transkript": "Transcrição", "PDF": "PDF", "An Teilnehmer": "Aos participantes", "Gedächtnis": "Memória", "Notion": "Notion", "Zusammenfassung": "Resumo",
    "Dein Meeting": "A sua reunião", "Bereit — Aufnahme noch nicht gestartet": "Pronto — gravação ainda não iniciada", "Mikro an": "Micro ligado", "Mikro aus": "Micro desligado",
    "📵 Gerät NICHT sperren & in dieser App bleiben — sonst pausiert die Aufnahme.": "📵 NÃO bloqueie o dispositivo e permaneça nesta app — caso contrário a gravação pausa.",
    "Beitritts-Code": "Código de acesso", "Oder Link teilen": "Ou partilhe o link", "Teilnehmer": "Participantes", "Noch niemand beigetreten…": "Ainda ninguém entrou…",
    "Ein-Geräte-Meeting": "Reunião de um dispositivo", "Alle sprechen über dieses Mikro. Starte die Aufnahme, wenn ihr bereit seid.": "Todos falam por este micro. Inicie a gravação quando estiverem prontos.",
    "Gib den 6-stelligen Code ein, den der Host teilt.": "Introduza o código de 6 dígitos partilhado pelo anfitrião.", "Meeting-Code": "Código da reunião", "Dein Name": "O seu nome", "E-Mail": "E-mail", "name@firma.de — optional": "nome@empresa.pt — opcional", "Beitreten": "Juntar-se",
    "Im Warteraum": "Na sala de espera", "Der Host muss dich noch freigeben…": "O anfitrião ainda tem de o admitir…", "Sobald der Host dich freigibt, startet deine Aufnahme automatisch.": "Assim que o anfitrião o admitir, a sua gravação começa automaticamente.", "Sobald der Host dich freigibt, bist du dabei.": "Assim que o anfitrião o admitir, está dentro.",
    "🔴 Aufnahme manuell starten": "🔴 Iniciar gravação manualmente", "Meeting verlassen": "Sair da reunião", "Du bist dabei": "Está dentro", "Warte auf Host…": "À espera do anfitrião…", "Sobald der Host startet, nimmt dein Gerät automatisch auf. Leg das Handy hin.": "Assim que o anfitrião iniciar, o teu dispositivo grava automaticamente. Pousa o telemóvel.",
    "Meeting beendet": "Reunião terminada", "Dein Deep-Dive wird erstellt — Transkript, Themen, Entscheidungen.": "A sua análise está a ser criada — transcrição, temas, decisões.",
    "Protokoll senden an…": "Enviar a ata para…", "Wähle die Empfänger. Fehlt eine E-Mail, kannst du sie hier eintragen.": "Escolha os destinatários. Se faltar um e-mail, pode adicioná-lo aqui.", "Freigeben": "Admitir", "Zur Startseite": "Para o início",
    "Protokoll-Sprache": "Idioma da ata", "Original-Sprache": "Idioma original", "Deutsch": "Alemão", "Englisch": "Inglês", "Spanisch": "Espanhol", "Französisch": "Francês", "Italienisch": "Italiano", "🌐 Automatisch erkennen": "🌐 Deteção automática",
    "🇩🇪 Deutsch": "🇩🇪 Alemão", "🇬🇧 Englisch": "🇬🇧 Inglês", "🇪🇸 Spanisch": "🇪🇸 Espanhol", "🇫🇷 Französisch": "🇫🇷 Francês", "🇮🇹 Italienisch": "🇮🇹 Italiano",
    "Meeting wird erstellt…": "A criar a reunião…", "Trete bei…": "A entrar…", "Sende…": "A enviar…", "Verbindungsfehler.": "Erro de ligação.", "Verbindungsfehler beim Erstellen.": "Erro de ligação ao criar.", "Host-Beitritt fehlgeschlagen.": "Falha na entrada do anfitrião.", "6-stelliger Code nötig.": "É necessário um código de 6 dígitos.", "Bitte Namen eingeben.": "Introduza um nome.", "E-Mail sieht ungültig aus — korrigieren oder leer lassen.": "O e-mail parece inválido — corrija ou deixe vazio.", "Beitritt fehlgeschlagen (Code korrekt? Meeting noch offen?).": "Falha ao entrar (código correto? reunião ainda aberta?).", "Meeting konnte nicht erstellt werden (Account-Zugang?).": "Não foi possível criar a reunião (acesso à conta?).", "Netzwerkfehler.": "Erro de rede.", "Aufnahme war unterbrochen — hier fortsetzen": "A gravação foi interrompida — retomar aqui", "Kopiert ✓": "Copiado ✓", "Geladen ✓": "Transferido ✓", "Transkript ✓": "Transcrição ✓", "Mikrofon": "Microfone", "Standard-Mikrofon": "Microfone predefinido", "Für ein zentrales Mikro (z. B. Jabra) hier das Gerät wählen — dann nimmt nur dieses auf.": "Para um micro central (p. ex. Jabra), escolha aqui o dispositivo — assim só este grava.", "Stimm-Check-In": "Check-in por voz", "Jeder liest seine Zahl vor — der Pod erkennt die Stimme und ordnet den Namen automatisch zu.": "Cada um lê o seu número em voz alta — o pod reconhece a voz e atribui o nome automaticamente.", "Stimm-Check-In starten": "Iniciar check-in por voz", "Starte…": "A iniciar…", "Du bist dran": "É a tua vez", "Lies deine Zahl laut vor:": "Lê o teu número em voz alta:", "Sprich deutlich Richtung Pod-Mikro.": "Fala com clareza em direção ao micro do pod.", "Der Pod hört zu…": "O pod está a ouvir…", "Geschafft": "Concluído", "Eingecheckt!": "Check-in feito!", "Alle dabei — es kann losgehen.": "Estão todos — vamos a isto.", "Stimme erkannt. Du kannst das Handy weglegen.": "Voz reconhecida. Podes pousar o telemóvel.", "liest gerade vor…": "está a ler agora…", "Gleich geht's los…": "Começamos já…", "Gleich bist du dran — halt dich bereit.": "És o próximo — prepara-te.", "eingecheckt": "com check-in", "✓ erkannt": "✓ reconhecido", "Test-Trigger (bis das echte Jabra die Zahl hört)": "Disparador de teste (até o Jabra real ouvir o número)", "Überspringen": "Saltar", "übersprungen": "saltado", "wartet": "a aguardar", "Alle eingecheckt ✓ — Aufnahme starten": "Todos com check-in ✓ — iniciar gravação",
  },
};

export const LANGS = ["de", "en", "es", "fr", "it", "pt"] as const;
export type Lang = (typeof LANGS)[number];

export function detectLang(): Lang {
  try {
    const s = localStorage.getItem("meetUiLang");
    if (s && (LANGS as readonly string[]).includes(s)) return s as Lang;
  } catch {
    /* ignore */
  }
  const n = (navigator.language || "de").toLowerCase();
  const m = LANGS.find((c) => n.startsWith(c));
  return m || "de";
}

/** Translate a German source string into the active language (German = identity). */
export function translate(lang: Lang, de: string): string {
  return lang === "de" ? de : (I18N[lang] && I18N[lang][de]) || de;
}

type LangCtx = { lang: Lang; setLang: (l: Lang) => void; t: (de: string) => string };
const Ctx = createContext<LangCtx | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(detectLang);
  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    try {
      localStorage.setItem("meetUiLang", l);
    } catch {
      /* ignore */
    }
    try {
      document.documentElement.lang = l;
    } catch {
      /* ignore */
    }
  }, []);
  const t = useCallback((de: string) => translate(lang, de), [lang]);
  return <Ctx.Provider value={{ lang, setLang, t }}>{children}</Ctx.Provider>;
}

export function useI18n(): LangCtx {
  const c = useContext(Ctx);
  if (!c) throw new Error("useI18n must be used within LangProvider");
  return c;
}
